name: flutter_customizable_calendar
description: a feature-rich Flutter package that offers highly customizable calendar views for displaying days, weeks, and months.
version: 0.0.1
homepage: https://github.com/Radency/flutter_customizable_calendar

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.6
  clock: ^1.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  intl: ^0.18.0
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
